package org.congcong.algomentor.identity.group.service;

public enum UserGroupErrorCode {
  USER_GROUP_NOT_FOUND,
  USER_GROUP_CODE_CONFLICT,
  USER_GROUP_DISABLED,
  USER_GROUP_DELETE_REQUIRES_DISABLED,
  USER_GROUP_INVALID_CODE,
  USER_GROUP_INVALID_EXPIRY,
  USER_GROUP_MEMBER_NOT_FOUND,
  USER_GROUP_BATCH_LIMIT_EXCEEDED,
  USER_GROUP_INVALID_REQUEST
}
