package org.congcong.algomentor.agent.core;

public enum AgentErrorCode {
  AGENT_RUN_IN_PROGRESS,
  UNKNOWN_TOOL,
  TOOL_NOT_ALLOWED,
  TOOL_EXECUTION_FAILED,
  LLM_STREAM_FAILED,
  MAX_STEPS_EXCEEDED,
  STRUCTURED_OUTPUT_INVALID,
  STRUCTURED_OUTPUT_UNSUPPORTED,
  STRUCTURED_OUTPUT_SCHEMA_INVALID,
  AGENT_EXECUTOR_OVERLOADED,
  AGENT_EXECUTOR_SHUTDOWN,
  CANCELLED,
  UNKNOWN
}
