package org.congcong.algomentor.auth.passwordreset;

public enum PasswordResetErrorCode {
  AUTH_PASSWORD_CREDENTIAL_NOT_FOUND,
  AUTH_PASSWORD_RESET_SELF_FORBIDDEN,
  AUTH_TEMPORARY_PASSWORD_EXPIRED,
  AUTH_TEMPORARY_PASSWORD_CONSUMED,
  AUTH_PASSWORD_CHANGE_REQUIRED,
  AUTH_PASSWORD_RESET_FAILED,
  AUTH_REQUEST_INVALID,
  USER_NOT_FOUND
}
