package org.congcong.algomentor.api.feedback.service;

/** 对外稳定的反馈错误码。 */
public enum FeedbackErrorCode {
  FEEDBACK_THREAD_NOT_FOUND,
  FEEDBACK_THREAD_FORBIDDEN,
  FEEDBACK_CATEGORY_INVALID,
  FEEDBACK_STATUS_INVALID,
  FEEDBACK_MESSAGE_INVALID,
  FEEDBACK_SOURCE_PATH_INVALID,
  FEEDBACK_SOURCE_RUN_INVALID,
  FEEDBACK_PAGE_INVALID
}
