package org.congcong.algomentor.llm.core;

public enum LlmErrorCode {
  INVALID_REQUEST,
  UNSUPPORTED_CAPABILITY,
  AUTHENTICATION_FAILED,
  PERMISSION_DENIED,
  RATE_LIMITED,
  TIMEOUT,
  PROVIDER_UNAVAILABLE,
  CONTENT_FILTERED,
  TOOL_CALL_INVALID,
  RESPONSE_PARSE_FAILED,
  CANCELLED,
  UNKNOWN
}
