package org.congcong.algomentor.api.learningplan.mapper.model;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.Instant;

public record LearningPlanTemplateRow(
    Long id,
    String templateId,
    String title,
    String titleEn,
    String summary,
    String summaryEn,
    String catalogCategory,
    Integer recommendedOrder,
    String intent,
    String goal,
    String goalEn,
    Integer defaultDurationWeeks,
    String level,
    Integer defaultWeeklyHours,
    String programmingLanguage,
    String difficultyPreference,
    JsonNode topicPreferencesJson,
    String targetAudience,
    String targetAudienceEn,
    JsonNode prerequisitesJson,
    JsonNode prerequisitesEnJson,
    JsonNode recommendedForJson,
    JsonNode recommendedForEnJson,
    JsonNode notRecommendedForJson,
    JsonNode notRecommendedForEnJson,
    String expectedOutcome,
    String expectedOutcomeEn,
    Boolean englishContentReady,
    String sourceName,
    String sourceUrl,
    String sourceCommit,
    String sourceDataPath,
    String sourceDescription,
    String curationNotes,
    String licenseNotice,
    Integer problemCount,
    Integer matchedProblemCount,
    Integer missingProblemCount,
    JsonNode metadataJson,
    Instant createdAt,
    Instant updatedAt
) {
}
