package org.congcong.algomentor.ai.governance.model;

public enum AiGovernanceErrorCode {
  AI_GLOBALLY_DISABLED,
  AI_USER_DISABLED,
  AI_RUNTIME_SETTINGS_INVALID,
  AI_USER_POLICY_INVALID,
  AI_MODEL_PRICE_NOT_FOUND,
  AI_MODEL_PRICE_ALREADY_EXISTS,
  AI_MODEL_PRICE_INVALID,
  AI_USAGE_DATE_RANGE_INVALID,
  AI_USAGE_QUERY_INVALID,
  AI_PROVIDER_DISABLED,
  AI_PURPOSE_DISABLED,
  AI_UNAUTHENTICATED,
  AI_FORBIDDEN,
  AI_QUOTA_EXCEEDED,
  AI_CONCURRENT_RUN_CONFLICT,
  AI_REQUEST_TOO_LARGE,
  AI_TIMEOUT,
  AI_RATE_LIMITED,
  AI_PROVIDER_UNAVAILABLE,
  AI_STRUCTURED_OUTPUT_INVALID,
  AI_CANCELLED,
  AI_UNKNOWN
}
