package org.congcong.algomentor.ai.governance.model;

public enum AiGovernanceErrorCode {
  AI_PROVIDER_DISABLED,
  AI_PURPOSE_DISABLED,
  AI_UNAUTHENTICATED,
  AI_FORBIDDEN,
  AI_QUOTA_EXCEEDED,
  AI_CONCURRENT_RUN_CONFLICT,
  AI_REQUEST_TOO_LARGE,
  AI_TIMEOUT,
  AI_RATE_LIMITED,
  AI_PROVIDER_UNAVAILABLE,
  AI_STRUCTURED_OUTPUT_INVALID,
  AI_CANCELLED,
  AI_UNKNOWN
}
