package org.congcong.algomentor.ai.governance.model;

public enum AiRunSource {
  LEARNING_PLAN_DRAFT,
  LEARNING_PLAN_DRAFT_REVISION,
  LEARNING_PLAN_EXTENSION_PROPOSAL,
  PROBLEM_DETAIL,
  LEARNING_CHAT,
  PRACTICE_CHAT,
  PRACTICE_CODE_REVIEW,
  RECALL_JUDGE,
  REVIEW_CARD_GENERATION,
  AI_DEBUG
}
