package org.congcong.algomentor.ai.governance.model;

public enum AiRunStatus {
  ADMITTED,
  REJECTED_QUOTA,
  REJECTED_CONCURRENT,
  REJECTED_DISABLED,
  REJECTED_UNAUTHENTICATED,
  REJECTED_FORBIDDEN,
  REJECTED_REQUEST_TOO_LARGE,
  RUNNING,
  COMPLETED,
  FAILED,
  CANCELLED,
  EXPIRED
}
