package org.congcong.algomentor.policy.service;

/** 管理写入与运行时解析共用的稳定错误码。 */
public enum GenericPolicyErrorCode {
  POLICY_NOT_FOUND,
  POLICY_INVALID_REQUEST,
  POLICY_INVALID_TYPE_CODE,
  POLICY_TYPE_NOT_REGISTERED,
  POLICY_INVALID_SUBJECT_RANGE,
  POLICY_SUBJECT_NOT_FOUND,
  POLICY_LIMIT_EXCEEDED,
  POLICY_CONTENT_TOO_LARGE,
  POLICY_CONTENT_COMPILE_FAILED,
  POLICY_VERSION_CONFLICT,
  POLICY_ORDER_CONFLICT,
  POLICY_ACCESS_DENIED,
  POLICY_RESOLUTION_FAILED
}
