package org.congcong.algomentor.auth.password;

/**
 * 用户主动管理登录密码接口使用的稳定错误码。
 */
public enum UserPasswordErrorCode {
  AUTH_PASSWORD_REQUEST_INVALID,
  AUTH_CURRENT_PASSWORD_REQUIRED,
  AUTH_CURRENT_PASSWORD_INVALID,
  AUTH_PASSWORD_CHANGE_REQUIRED,
  AUTH_PASSWORD_UPDATE_NOT_ALLOWED,
  AUTH_PASSWORD_LOGIN_EMAIL_UNAVAILABLE,
  AUTH_PASSWORD_CHANGED_CONCURRENTLY,
  AUTH_PASSWORD_UPDATE_FAILED
}
