package org.congcong.algomentor.mentor.application.profile;

/** 学习者画像的固定维度，不能由模型自由扩展。 */
public enum LearnerMemoryClaimDimension {
  LEARNER_BACKGROUND,
  GOALS_AND_INTENTS,
  TIME_AND_RESOURCE_CONSTRAINTS,
  LEARNING_AND_INTERACTION_PREFERENCES,
  SELF_ABILITY_ASSESSMENT,
  PROBLEM_SOLVING_APPROACH,
  IMPLEMENTATION_AND_ERROR_PATTERN,
  LEARNING_INTERACTION_AND_INDEPENDENCE,
  REVIEW_AND_GROWTH_PERFORMANCE,
  TAG_MASTERY
}
