import { ArrowLeft, BookOpen, CheckCircle2, Clock3, Layers3, RotateCcw, Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { APP_ROUTES } from './app/navigation';
import MarkdownView from './components/MarkdownView';
import { useI18n } from './i18n/I18nProvider';

type Topic = { id: number; title: string; summary?: string; directCardCount: number; subtreeCardCount: number; subtreeEnrolledCardCount: number };
type OutlineNode = { node: { id: number }; children?: OutlineNode[] };
type LearningState = { enrolled: boolean; isDue: boolean; phase?: string };
type Card = { id: number; question: string; answerMarkdown?: string; learningState: LearningState };

async function get<T>(path: string): Promise<T> {
  const response = await fetch(path, { credentials: 'include', headers: { Accept: 'application/json' } });
  const payload = await response.json().catch(() => undefined);
  if (!response.ok || !payload?.success) throw new Error(payload?.error?.message || `请求失败（${response.status}）`);
  return payload.data as T;
}
function collectNodeIds(tree: OutlineNode): number[] { return [tree.node.id, ...(tree.children ?? []).flatMap(collectNodeIds)]; }

export default function KnowledgePage({ onNavigate }: { onNavigate?: (path: string) => void } = {}) {
  const { locale, resources } = useI18n();
  const [topics, setTopics] = useState<Topic[]>([]); const [topic, setTopic] = useState<Topic>();
  const [cards, setCards] = useState<Card[]>([]); const [selected, setSelected] = useState<Card>();
  const [answer, setAnswer] = useState(false); const [loading, setLoading] = useState(true); const [cardsLoading, setCardsLoading] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  useEffect(() => { const controller = new AbortController(); setLoading(true); get<{ items: Topic[] }>('/api/knowledge/topics').then((data) => setTopics(data.items ?? [])).catch((e: Error) => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [locale]);
  async function open(nextTopic: Topic) { setTopic(nextTopic); setSelected(undefined); setCards([]); setQuery(''); setError(''); setCardsLoading(true); try { const tree = await get<OutlineNode>(`/api/knowledge/outline-nodes/${nextTopic.id}/tree`); const pages = await Promise.all(collectNodeIds(tree).map((id) => get<{ items: Card[] }>(`/api/knowledge/outline-nodes/${id}/cards`))); setCards(pages.flatMap((page) => page.items ?? [])); } catch (e) { setError((e as Error).message); } finally { setCardsLoading(false); } }
  async function selectCard(card: Card) { setSelected(card); setAnswer(false); setError(''); try { setSelected(await get<Card>(`/api/knowledge/cards/${card.id}`)); } catch (e) { setError((e as Error).message); } }
  async function review(rating: string) { if (!selected) return; try { const response = await fetch(`/api/knowledge/cards/${selected.id}/review-attempts`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ clientAttemptId: crypto.randomUUID(), rating, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }) }); const payload = await response.json().catch(() => undefined); if (!response.ok || !payload?.success) throw new Error(payload?.error?.message || `请求失败（${response.status}）`); setSelected({ ...selected, learningState: { ...selected.learningState, enrolled: true, isDue: false } }); setCards((current) => current.map((card) => card.id === selected.id ? { ...card, learningState: { ...card.learningState, enrolled: true, isDue: false } } : card)); } catch (e) { setError((e as Error).message); } }
  const filteredCards = useMemo(() => { const normalized = query.trim().toLowerCase(); return normalized ? cards.filter((card) => card.question.toLowerCase().includes(normalized)) : cards; }, [cards, query]);
  const totalCards = topics.reduce((sum, item) => sum + (item.subtreeCardCount ?? item.directCardCount ?? 0), 0); const enrolledCards = topics.reduce((sum, item) => sum + (item.subtreeEnrolledCardCount ?? 0), 0);
  return <section className="knowledge-page" aria-labelledby="knowledge-title">
    <header className="knowledge-header"><div><p className="knowledge-eyebrow"><BookOpen aria-hidden="true" /> {resources.nav.knowledge}</p><h1 id="knowledge-title">知识库</h1><p className="knowledge-subtitle">按技术主题浏览高频知识卡，随时加入复习中心巩固记忆。</p></div><button className="secondary-button" onClick={() => onNavigate?.(APP_ROUTES.knowledgeReview)} type="button"><RotateCcw aria-hidden="true" /> 查看复习中心</button></header>
    <dl className="knowledge-stat-grid" aria-label="知识库概览"><div><dt>技术主题</dt><dd>{topics.length}</dd></div><div><dt>知识卡片</dt><dd>{totalCards}</dd></div><div><dt>已加入复习</dt><dd>{enrolledCards}</dd></div></dl>
    {error && <p className="error-text" role="alert">{error}</p>}
    {loading ? <div className="loading-panel" role="status">正在加载知识库…</div> : !topic ? <div className="knowledge-topic-grid">{topics.length === 0 ? <div className="loading-panel">暂无知识主题。</div> : topics.map((item) => <button className="knowledge-topic-card" key={item.id} onClick={() => void open(item)} type="button"><span className="knowledge-topic-icon"><Layers3 aria-hidden="true" /></span><span className="knowledge-topic-copy"><strong>{item.title}</strong><span>{item.summary || '整理核心概念与常见面试问法。'}</span></span><span className="knowledge-topic-meta">{item.subtreeCardCount ?? item.directCardCount} 张卡片 <b>·</b> 已复习 {item.subtreeEnrolledCardCount ?? 0}</span></button>)}</div> : <div className="knowledge-workspace"><section className="knowledge-browser" aria-labelledby="knowledge-topic-title"><div className="knowledge-browser-header"><button className="secondary-button compact" onClick={() => { setTopic(undefined); setSelected(undefined); }} type="button"><ArrowLeft aria-hidden="true" /> 返回主题</button><div><p className="eyebrow">当前主题</p><h2 id="knowledge-topic-title">{topic.title}</h2></div></div><label className="search-field knowledge-search"><Search aria-hidden="true" /><input onChange={(event) => setQuery(event.target.value)} placeholder="搜索知识卡" value={query} /></label><div className="knowledge-card-list" aria-busy={cardsLoading}>{cardsLoading ? <div className="loading-panel">正在加载知识卡…</div> : filteredCards.length === 0 ? <div className="loading-panel">没有匹配的知识卡。</div> : filteredCards.map((card) => <button className={`knowledge-card-row ${selected?.id === card.id ? 'selected' : ''}`} key={card.id} onClick={() => void selectCard(card)} type="button"><span>{card.question}</span><small>{card.learningState.enrolled ? (card.learningState.isDue ? '今日待复习' : '复习中') : '未加入复习'}</small></button>)}</div></section><article className="knowledge-detail learning-panel" aria-live="polite">{selected ? <><div className="knowledge-detail-heading"><span className="knowledge-detail-label">知识卡 #{selected.id}</span><span className="status-pill"><Clock3 aria-hidden="true" /> {selected.learningState.enrolled ? '复习中' : '未加入复习'}</span></div><h2>{selected.question}</h2>{!answer ? <div className="knowledge-answer-gate"><p>先在脑中回忆答案，再查看完整解析。</p><button className="primary-button" onClick={() => setAnswer(true)} type="button">显示答案</button></div> : <><div className="knowledge-answer"><MarkdownView content={selected.answerMarkdown || '暂无答案。'} /></div><div className="knowledge-review-actions"><span>完成回忆后选择熟练度</span><div className="button-row">{(['AGAIN', 'HARD', 'GOOD', 'EASY'] as const).map((rating) => <button className="secondary-button" key={rating} onClick={() => void review(rating)} type="button">{resources.reviewCenter.ratingLabels[rating]}</button>)}</div></div></>}</> : <div className="knowledge-empty-detail"><CheckCircle2 aria-hidden="true" /><h2>选择一张知识卡开始学习</h2><p>从左侧列表挑选主题卡片，先回忆，再记录复习结果。</p></div>}</article></div>}
  </section>;
}
