import { RefreshCw } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { ApiRequestError, getAdminOverview, requireApiData } from '../../services/api';
import type { AdminOverview } from '../../types/api';
import AdminOverviewSection from './AdminOverviewSection';

export default function AdminOverviewPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [overview, setOverview] = useState<AdminOverview>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const abortRef = useRef<AbortController | undefined>(undefined);
  useEffect(() => { void load(); const interval = window.setInterval(() => { if (!document.hidden) void load(); }, 60_000); return () => { abortRef.current?.abort(); window.clearInterval(interval); }; }, []);
  async function load() { abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setLoading(true); try { setOverview(requireApiData(await getAdminOverview(controller.signal), '管理员概览加载失败')); setError(''); } catch (caught) { if (!controller.signal.aborted) setError(caught instanceof ApiRequestError || caught instanceof Error ? caught.message : '管理员概览加载失败'); } finally { if (!controller.signal.aborted) setLoading(false); } }
  if (loading && !overview) return <section className="admin-overview-page"><p>正在加载管理员概览...</p></section>;
  if (!overview) return <section className="admin-overview-page"><h1>管理员概览</h1><p className="error-text">{error}</p><button className="secondary-button" onClick={() => void load()} type="button">重试</button></section>;
  return <section className="admin-overview-page"><header className="admin-overview-header"><div><h1>管理员概览</h1><p>数据时间：{new Date(overview.generatedAt).toLocaleString()} · 配额时区：{overview.quotaZone}</p>{error ? <p className="error-text">{error}</p> : null}</div><button aria-label="刷新" className="icon-button" onClick={() => void load()} title="刷新" type="button"><RefreshCw aria-hidden="true" /></button></header><div className="admin-overview-status-row"><AdminOverviewSection section={overview.betaAccess} title="内测准入">{data => <button className="overview-link-button" onClick={() => onNavigate('/admin/beta-access')} type="button">{data.emailAllowlistEnabled ? '已开启' : '已关闭'} · {data.allowedEmailCount} 人 / 已注册 {data.registeredAllowedEmailCount} 人</button>}</AdminOverviewSection><AdminOverviewSection section={overview.aiRuntime} title="AI 运行策略">{data => <button className="overview-link-button" onClick={() => onNavigate('/admin/ai')} type="button">{data.aiEnabled ? '已开启' : '已关闭'} · 默认 {data.defaultDailyRequestLimit} 次</button>}</AdminOverviewSection></div><div className="admin-overview-metrics"><AdminOverviewSection section={overview.aiToday} title="今日 AI 使用">{data => <><dl><div><dt>入口请求</dt><dd>{data.entryRequests.total}</dd></div><div><dt>成功</dt><dd>{data.entryRequests.completed}</dd></div><div><dt>失败</dt><dd>{data.entryRequests.failed}</dd></div><div><dt>额度拒绝</dt><dd>{data.entryRequests.quotaRejected}</dd></div><div><dt>模型调用</dt><dd>{data.modelCallCount}</dd></div><div><dt>Token</dt><dd>{data.totalTokens.toLocaleString()}</dd></div><div><dt>按当前价格估算</dt><dd>${data.estimatedCostUsd}</dd></div></dl>{data.unpricedCallCount > 0 ? <button className="warning-link" onClick={() => onNavigate('/admin/ai?tab=pricing')} type="button">{data.unpricedCallCount} 次未定价调用</button> : null}</>}</AdminOverviewSection></div><div className="admin-overview-columns"><AdminOverviewSection section={overview.quotaRisks} title="额度风险用户">{data => data.items.length ? <ul className="overview-list">{data.items.map(item => <li key={item.userId}><button onClick={() => onNavigate(`/admin/users?userId=${item.userId}`)} type="button">{item.displayName || item.email || `用户 ${item.userId}`}</button><span>{item.requestCount} / {item.effectiveDailyRequestLimit} · {item.usagePercent}%</span></li>)}</ul> : <p>暂无接近额度上限的用户。</p>}</AdminOverviewSection><AdminOverviewSection section={overview.feedback} title="反馈待办">{data => <div className="overview-feedback-links"><button onClick={() => onNavigate('/admin/feedback?status=OPEN')} type="button">OPEN {data.openThreadCount}</button><button onClick={() => onNavigate('/admin/feedback?unreadOnly=true')} type="button">管理员未读 {data.adminUnreadMessageCount}</button></div>}</AdminOverviewSection></div><AdminOverviewSection section={overview.recentFailedRuns} title="最近失败 run">{data => data.items.length ? <p>{data.items.length} 个失败 run</p> : <p>暂未提供 run 查询。</p>}</AdminOverviewSection></section>;
}
